project:
  type: website

website:
  title: "Amali Rajapaksha"

  navbar:
    background: "#0f172a"
    foreground: "#f8fafc"
    left:
      - text: About
        href: about.qmd
      - text: Software
        href: Software.qmd
      - text: Projects
        href: Projects.qmd
      - text: Certifications
        href: Certifications.qmd
      - text: Experience
        href: Experience.qmd
      - text: Blog
        href: Blog.qmd  
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

